import hljs from 'highlight.js/lib/core';
import lang_actionscript from 'highlight.js/lib/languages/actionscript';
import lang_ada from 'highlight.js/lib/languages/ada';
import lang_angelscript from 'highlight.js/lib/languages/angelscript';
import lang_apache from 'highlight.js/lib/languages/apache';
import lang_applescript from 'highlight.js/lib/languages/applescript';
import lang_arduino from 'highlight.js/lib/languages/arduino';
import lang_asciidoc from 'highlight.js/lib/languages/asciidoc';
import lang_autohotkey from 'highlight.js/lib/languages/autohotkey';
import lang_awk from 'highlight.js/lib/languages/awk';
import lang_bash from 'highlight.js/lib/languages/bash';
import lang_basic from 'highlight.js/lib/languages/basic';
import lang_bnf from 'highlight.js/lib/languages/bnf';
import lang_c from 'highlight.js/lib/languages/c';
import lang_cal from 'highlight.js/lib/languages/cal';
import lang_clojure from 'highlight.js/lib/languages/clojure';
import lang_cmake from 'highlight.js/lib/languages/cmake';
import lang_coq from 'highlight.js/lib/languages/coq';
import lang_cpp from 'highlight.js/lib/languages/cpp';
import lang_crystal from 'highlight.js/lib/languages/crystal';
import lang_csharp from 'highlight.js/lib/languages/csharp';
import lang_csp from 'highlight.js/lib/languages/csp';
import lang_css from 'highlight.js/lib/languages/css';
import lang_d from 'highlight.js/lib/languages/d';
import lang_dart from 'highlight.js/lib/languages/dart';
import lang_delphi from 'highlight.js/lib/languages/delphi';
import lang_diff from 'highlight.js/lib/languages/diff';
import lang_dns from 'highlight.js/lib/languages/dns';
import lang_dockerfile from 'highlight.js/lib/languages/dockerfile';
import lang_dos from 'highlight.js/lib/languages/dos';
import lang_dts from 'highlight.js/lib/languages/dts';
import lang_dust from 'highlight.js/lib/languages/dust';
import lang_ebnf from 'highlight.js/lib/languages/ebnf';
import lang_elixir from 'highlight.js/lib/languages/elixir';
import lang_elm from 'highlight.js/lib/languages/elm';
import lang_erlang from 'highlight.js/lib/languages/erlang';
import lang_excel from 'highlight.js/lib/languages/excel';
import lang_fix from 'highlight.js/lib/languages/fix';
import lang_flix from 'highlight.js/lib/languages/flix';
import lang_fortran from 'highlight.js/lib/languages/fortran';
import lang_fsharp from 'highlight.js/lib/languages/fsharp';
import lang_glsl from 'highlight.js/lib/languages/glsl';
import lang_go from 'highlight.js/lib/languages/go';
import lang_gradle from 'highlight.js/lib/languages/gradle';
import lang_graphql from 'highlight.js/lib/languages/graphql';
import lang_groovy from 'highlight.js/lib/languages/groovy';
import lang_haml from 'highlight.js/lib/languages/haml';
import lang_haskell from 'highlight.js/lib/languages/haskell';
import lang_haxe from 'highlight.js/lib/languages/haxe';
import lang_hsp from 'highlight.js/lib/languages/hsp';
import lang_http from 'highlight.js/lib/languages/http';
import lang_ini from 'highlight.js/lib/languages/ini';
import lang_java from 'highlight.js/lib/languages/java';
import lang_javascript from 'highlight.js/lib/languages/javascript';
import lang_json from 'highlight.js/lib/languages/json';
import lang_julia from 'highlight.js/lib/languages/julia';
import lang_kotlin from 'highlight.js/lib/languages/kotlin';
import lang_lasso from 'highlight.js/lib/languages/lasso';
import lang_latex from 'highlight.js/lib/languages/latex';
import lang_ldif from 'highlight.js/lib/languages/ldif';
import lang_leaf from 'highlight.js/lib/languages/leaf';
import lang_lisp from 'highlight.js/lib/languages/lisp';
import lang_livescript from 'highlight.js/lib/languages/livescript';
import lang_llvm from 'highlight.js/lib/languages/llvm';
import lang_lua from 'highlight.js/lib/languages/lua';
import lang_makefile from 'highlight.js/lib/languages/makefile';
import lang_markdown from 'highlight.js/lib/languages/markdown';
import lang_matlab from 'highlight.js/lib/languages/matlab';
import lang_mel from 'highlight.js/lib/languages/mel';
import lang_mercury from 'highlight.js/lib/languages/mercury';
import lang_nginx from 'highlight.js/lib/languages/nginx';
import lang_nim from 'highlight.js/lib/languages/nim';
import lang_nix from 'highlight.js/lib/languages/nix';
import lang_ocaml from 'highlight.js/lib/languages/ocaml';
import lang_perl from 'highlight.js/lib/languages/perl';
import lang_php from 'highlight.js/lib/languages/php';
import lang_plaintext from 'highlight.js/lib/languages/plaintext';
import lang_powershell from 'highlight.js/lib/languages/powershell';
import lang_prolog from 'highlight.js/lib/languages/prolog';
import lang_properties from 'highlight.js/lib/languages/properties';
import lang_protobuf from 'highlight.js/lib/languages/protobuf';
import lang_puppet from 'highlight.js/lib/languages/puppet';
import lang_python from 'highlight.js/lib/languages/python';
import lang_qml from 'highlight.js/lib/languages/qml';
import lang_r from 'highlight.js/lib/languages/r';
import lang_reasonml from 'highlight.js/lib/languages/reasonml';
import lang_rib from 'highlight.js/lib/languages/rib';
import lang_ruby from 'highlight.js/lib/languages/ruby';
import lang_ruleslanguage from 'highlight.js/lib/languages/ruleslanguage';
import lang_rust from 'highlight.js/lib/languages/rust';
import lang_sas from 'highlight.js/lib/languages/sas';
import lang_scala from 'highlight.js/lib/languages/scala';
import lang_scheme from 'highlight.js/lib/languages/scheme';
import lang_scss from 'highlight.js/lib/languages/scss';
import lang_shell from 'highlight.js/lib/languages/shell';
import lang_smalltalk from 'highlight.js/lib/languages/smalltalk';
import lang_sql from 'highlight.js/lib/languages/sql';
import lang_swift from 'highlight.js/lib/languages/swift';
import lang_tcl from 'highlight.js/lib/languages/tcl';
import lang_typescript from 'highlight.js/lib/languages/typescript';
import lang_vala from 'highlight.js/lib/languages/vala';
import lang_vbnet from 'highlight.js/lib/languages/vbnet';
import lang_verilog from 'highlight.js/lib/languages/verilog';
import lang_vhdl from 'highlight.js/lib/languages/vhdl';
import lang_vim from 'highlight.js/lib/languages/vim';
import lang_wasm from 'highlight.js/lib/languages/wasm';
import lang_xml from 'highlight.js/lib/languages/xml';
import lang_yaml from 'highlight.js/lib/languages/yaml';

hljs.registerLanguage('actionscript', lang_actionscript);
hljs.registerLanguage('ada', lang_ada);
hljs.registerLanguage('angelscript', lang_angelscript);
hljs.registerLanguage('apache', lang_apache);
hljs.registerLanguage('applescript', lang_applescript);
hljs.registerLanguage('arduino', lang_arduino);
hljs.registerLanguage('xml', lang_xml);
hljs.registerLanguage('asciidoc', lang_asciidoc);
hljs.registerLanguage('autohotkey', lang_autohotkey);
hljs.registerLanguage('awk', lang_awk);
hljs.registerLanguage('bash', lang_bash);
hljs.registerLanguage('basic', lang_basic);
hljs.registerLanguage('bnf', lang_bnf);
hljs.registerLanguage('c', lang_c);
hljs.registerLanguage('cal', lang_cal);
hljs.registerLanguage('clojure', lang_clojure);
hljs.registerLanguage('cmake', lang_cmake);
hljs.registerLanguage('coq', lang_coq);
hljs.registerLanguage('cpp', lang_cpp);
hljs.registerLanguage('crystal', lang_crystal);
hljs.registerLanguage('csharp', lang_csharp);
hljs.registerLanguage('csp', lang_csp);
hljs.registerLanguage('css', lang_css);
hljs.registerLanguage('d', lang_d);
hljs.registerLanguage('markdown', lang_markdown);
hljs.registerLanguage('dart', lang_dart);
hljs.registerLanguage('delphi', lang_delphi);
hljs.registerLanguage('diff', lang_diff);
hljs.registerLanguage('dns', lang_dns);
hljs.registerLanguage('dockerfile', lang_dockerfile);
hljs.registerLanguage('dos', lang_dos);
hljs.registerLanguage('dts', lang_dts);
hljs.registerLanguage('dust', lang_dust);
hljs.registerLanguage('ebnf', lang_ebnf);
hljs.registerLanguage('elixir', lang_elixir);
hljs.registerLanguage('elm', lang_elm);
hljs.registerLanguage('ruby', lang_ruby);
hljs.registerLanguage('erlang', lang_erlang);
hljs.registerLanguage('excel', lang_excel);
hljs.registerLanguage('fix', lang_fix);
hljs.registerLanguage('flix', lang_flix);
hljs.registerLanguage('fortran', lang_fortran);
hljs.registerLanguage('fsharp', lang_fsharp);
hljs.registerLanguage('glsl', lang_glsl);
hljs.registerLanguage('go', lang_go);
hljs.registerLanguage('gradle', lang_gradle);
hljs.registerLanguage('graphql', lang_graphql);
hljs.registerLanguage('groovy', lang_groovy);
hljs.registerLanguage('haml', lang_haml);
hljs.registerLanguage('haskell', lang_haskell);
hljs.registerLanguage('haxe', lang_haxe);
hljs.registerLanguage('hsp', lang_hsp);
hljs.registerLanguage('http', lang_http);
hljs.registerLanguage('ini', lang_ini);
hljs.registerLanguage('java', lang_java);
hljs.registerLanguage('javascript', lang_javascript);
hljs.registerLanguage('json', lang_json);
hljs.registerLanguage('julia', lang_julia);
hljs.registerLanguage('kotlin', lang_kotlin);
hljs.registerLanguage('lasso', lang_lasso);
hljs.registerLanguage('latex', lang_latex);
hljs.registerLanguage('ldif', lang_ldif);
hljs.registerLanguage('leaf', lang_leaf);
hljs.registerLanguage('lisp', lang_lisp);
hljs.registerLanguage('livescript', lang_livescript);
hljs.registerLanguage('llvm', lang_llvm);
hljs.registerLanguage('lua', lang_lua);
hljs.registerLanguage('makefile', lang_makefile);
hljs.registerLanguage('matlab', lang_matlab);
hljs.registerLanguage('mel', lang_mel);
hljs.registerLanguage('mercury', lang_mercury);
hljs.registerLanguage('perl', lang_perl);
hljs.registerLanguage('nginx', lang_nginx);
hljs.registerLanguage('nim', lang_nim);
hljs.registerLanguage('nix', lang_nix);
hljs.registerLanguage('ocaml', lang_ocaml);
hljs.registerLanguage('php', lang_php);
hljs.registerLanguage('plaintext', lang_plaintext);
hljs.registerLanguage('powershell', lang_powershell);
hljs.registerLanguage('prolog', lang_prolog);
hljs.registerLanguage('properties', lang_properties);
hljs.registerLanguage('protobuf', lang_protobuf);
hljs.registerLanguage('puppet', lang_puppet);
hljs.registerLanguage('python', lang_python);
hljs.registerLanguage('qml', lang_qml);
hljs.registerLanguage('r', lang_r);
hljs.registerLanguage('reasonml', lang_reasonml);
hljs.registerLanguage('rib', lang_rib);
hljs.registerLanguage('ruleslanguage', lang_ruleslanguage);
hljs.registerLanguage('rust', lang_rust);
hljs.registerLanguage('sas', lang_sas);
hljs.registerLanguage('scala', lang_scala);
hljs.registerLanguage('scheme', lang_scheme);
hljs.registerLanguage('scss', lang_scss);
hljs.registerLanguage('shell', lang_shell);
hljs.registerLanguage('smalltalk', lang_smalltalk);
hljs.registerLanguage('sql', lang_sql);
hljs.registerLanguage('swift', lang_swift);
hljs.registerLanguage('yaml', lang_yaml);
hljs.registerLanguage('tcl', lang_tcl);
hljs.registerLanguage('typescript', lang_typescript);
hljs.registerLanguage('vala', lang_vala);
hljs.registerLanguage('vbnet', lang_vbnet);
hljs.registerLanguage('verilog', lang_verilog);
hljs.registerLanguage('vhdl', lang_vhdl);
hljs.registerLanguage('vim', lang_vim);
hljs.registerLanguage('wasm', lang_wasm);

export default hljs;
